DanBloomberg/leptonica

src/colorquant1.c, src/makefile.static
=> Fix typos found by codespell

src/bmpio.c, src/jp2kio.c, src/jpegio.c, src/pngio.c, src/pnmio.c
=> Remove unneeded extern declarations

README.html
* Write some names in the usual upper case.
* Remove outdated information on Debian.
=> Update and improve README.html

src/pix1.c, src/pix2.c, src/pix3.c, src/pix4.c, src/pix5.c
=> pix?.c: fix doxygen warnings + conv. bugs

prog/ptra1_reg.c
=> Remove unused local code (CopyPtras)

src/boxfunc4.c
=> Remove unused local function boxaMaximizeEvenOddHeight

README.md, src/boxfunc1.c
seems to fix the broken build that https://github.com/DanBloomberg/leptonica/commit/7ba075514b7231538bcedd2749a23bdb7b40e0a8 seems to have caused.
=> fix build breaker

README.md, src/boxfunc1.c
Reverts DanBloomberg/leptonica#203
=> Revert "fix build breaker"

src/tiffio.c, src/utils.c
=> Fix two bugs (reported by Coverity Scan)

src/bardecode.c, src/bbuffer.c, src/bilateral.c
=> Fix some resource leaks (reported by Coverity Scan)

src/gifio.c, src/readfile.c, src/utils1.c
=> Fix some comments (typos, grammar)

CMakeLists.txt, lept.pc.cmake, prog/CMakeLists.txt, src/CMakeLists.txt
I don`t know what exactly programs need to be installed, so I took the option from Makefile.am.
Probably fix #117
=> cmake install configuration

prog/arabic_lines.c, prog/recogtest3.c
=> Fix typo in comment (found by codespell)

src/sarray1.c
Portability means source code portability (this is true that Solaris-based systems lack `d_type`) and runtime portability which means that the application should always test for `d_type == DT_UNKNOWN` (some filesystems may not set `d_type`).
Ref. https://www.osdyson.org/projects/dyson/wiki/Particular_recipes#Missing-d_type-of-struct-dirent
=> Use portable fstatat instead of dirent.d_type

src/readbarcode.c
=> Fix CID 1365421, CID 1365459 (Uninitialized scalar variable)

README.html, cmake/Configure.cmake, configure.ac, cppan.yml, src/environ.h, src/makefile.static, src/sarray1.c, sw.cpp
Fixes: DanBloomberg/leptonica#327
=> Add `fstatat()` availibility autodetection/configuration and replace with `stat()` if necessary

prog/Makefile.am
=> Add some missing test programs to list of other programs

prog/findpattern1.c, prog/livre_hmt.c, src/adaptmap.c, src/affine.c, src/affinecompose.c, src/binarize.c, src/blend.c, src/dewarp1.c, src/dewarp2.c, src/dewarp4.c, src/dnafunc1.c, src/encoding.c, src/environ.h, src/jbclass.c, src/pix.h, src/pix1.c, src/ptra.c, src/recogident.c, src/recogtrain.c, src/selgen.c, src/skew.c, src/stringcode.h, src/tiffio.c, version-notes.html
=> Fix some typos (found by codespell)

src/boxfunc4.c, src/pixafunc2.c
=> Fix some errors reported by Coverity Scan

src/CMakeLists.txt
Create symlink (for unix like os) with autotools library name (lept)
=> support tesseract autotools leptonica name

lept.pc.in
=> add missing LIBJP2K to lept.pc; fixes #395

CMakeLists.txt, configure.ac, lept.pc.cmake, lept.pc.in, src/CMakeLists.txt
- fix #433
- Workaround for #436
=> Cmake fixes

src/morph.c
=> Fix CID 1489035 (resource leak)

prog/fuzzing/barcode_fuzzer.cc
Adding a new fuzzer for the barcode-part of the library.
=> Added new fuzzer

prog/fuzzing/pix1_fuzzer.cc
This PR adds a fuzzer for targets in pix1.c that need to be explicitly called to be covered.
=> [pix1.c] Added fuzzer

prog/fuzzing/pageseg_fuzzer.cc
This PR adds a fuzzer for targets in `pageseg.c`
=> [pageseg.c] Added fuzzer

prog/fuzzing/recog_basic.cc
This PR adds a fuzzer that targets `recogRead()`
=> [recogbasic.c] Added fuzzer

prog/fuzzing/pix4_fuzzer.cc
This PR adds a fuzzer that targets the functions in pix4.c that need to be explicitly called in order to be covered.
=> [pix4.c] Added fuzzer

prog/fuzzing/boxfunc3_fuzzer.cc, prog/fuzzing/boxfunc4_fuzzer.cc, prog/fuzzing/boxfunc5_fuzzer.cc
This PR adds 3 fuzzers.
Each file contains targets of the related source-file that must be called explicitly in order to be covered.
The targets in boxfunc3_fuzzer.cc may not seem obvious, and comments above each section clarify what the target of the given section is.
=> Added 3 new fuzzers

prog/affine_reg.c
=> affine_reg: Fix memory leak

CMakeLists.txt
fixes policy CMP0054; fixes #547 issue
=> cmake: increase minimum version to 3.1.3; 

Makefile.am, prog/fuzzing/adaptmap_fuzzer.cc, prog/fuzzing/affine_fuzzer.cc, prog/fuzzing/bilateral_fuzzer.cc, prog/fuzzing/bilinear_fuzzer.cc, prog/fuzzing/binarize_fuzzer.cc, prog/fuzzing/blend_fuzzer.cc, prog/fuzzing/checkerboard_fuzzer.cc, prog/fuzzing/classapp_fuzzer.cc, prog/fuzzing/oss-fuzz-build.sh
This PR rewrites the blend_fuzzer and adds new fuzzers.
Furthermore compilation for seed corpus for the fuzzers has been added.
=> Added fuzzers, rewrote an existing fuzzer

src/readbarcode.c
=> Fix CID 1499794 (Dereference after null check)

prog/fuzzing/blend_fuzzer.cc, prog/fuzzing/ccthin_fuzzer.cc, prog/fuzzing/colorquant_fuzzer.cc, prog/fuzzing/compare_fuzzer.cc, prog/fuzzing/morph_fuzzer.cc
This PR adds more targets to existing fuzzers as well as a new ccthin_fuzzer
=> Added more fuzzers

src/pnmio.c
The goal is to make it possible
to read a PNM/PAM image from stdin (netpbm-like),
which is currently not working: see issue #580.
The reason is the use of fseek(fp, -1, SEEK_CUR)
to "go back" after a fgetc(),
which doesn't work for stdin,
so it has been replaced through fscanf().
=> pnmio.c: avoid fseek()

src/binarize.c, src/boxfunc3.c, src/pix1.c
=> Fix some small typos in comments

README.md
=> Remove Coverity scan build status (too many false positives)

src/dnabasic.c, src/numabasic.c, src/sarray1.c
=> Fix documentation

src/array.h, src/boxbasic.c, src/bytearray.c, src/ccbord.c, src/ccbord.h, src/dnabasic.c, src/environ.h, src/fpix1.c, src/numabasic.c, src/pix.h, src/pix1.c, src/pixabasic.c, src/ptabasic.c, src/sarray1.c
=> Use atomic operations for reference counters

src/rbtree.c
=> Remove PROCNAME / procName and use __func__

configure.ac
Fixes: 29a33a364848f67d ("Modify makefile.static and Makefile.am [...]")
=> Update library name for pkg-config

prog/fuzzing/binarize_fuzzer.cc, prog/fuzzing/oss-fuzz-build.sh
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49777
Fixes: https://github.com/google/oss-fuzz/issues/8152
=> Fix oss-fuzz build failure

src/pix1.c
=> Fix memory leak (Coverity Scan #1527427)

src/classapp.c
=> Fix typo callof -> calloc and fix six Coverity Scan issues

src/pdfio2.c
=> Fix memory leak (Coverity Scan #1503047)

README.md
=> Remove LGTM badges (LGTM.com will be shut down in December 2022)

prog/pageseg_reg.c
=> Fix memory leak in pageseg_reg

src/sarray1.c
There is no PATH_MAX limitation on GNU/Hurd, and realpath() can be safely be used with its second parameter set to NULL (as required by posix since its version 2001).
=> Fix GNU/Hurd build

CMakeLists.txt
=> CMakeLists.txt: Remove remainng 'cxx'

.github/workflows/cmake.yml
Try building these to see if #759 can be reproduced on Linux runner.
=> cmake.yml: test building programs
