DanBloomberg/leptonica

- src/allheaders.h
- src/utils.c
Commit ca9d16af54074812331fbc08a76a0410f6955796 introduced
a new function fopenWriteWinTempfile, but used
fopenWriteWinTmpfile for the implementation.
This caused builds for Windows to fail.
> Fix typo in function name (regression for Windows builds)

- src/utils.c
* Remove unneeded extern declaration for function fmemopen.
* Use existing function fopenWriteWinTempfile for fopenReadStream.
* Compile function fopenWriteWinTempfile only for Windows.
* Visual Studio does not provide the function mkstemp.
Replace it by a combination of genTempFilename and _open.
* Replace the deprecated fdopen by _fdopen.
* Use "r+b" when calling _fdopen. It is sufficient there as it is not
necessary to erase existing data in the file.
> Clean handling of temporary files and fix compilation for Windows

- src/utils.c
src/utils.c uses the macro HAVE_FMEMOPEN which comes from config_auto.h,
so it must include that file.
> Fix use of fmemopen in src/utils.c

- src/makefile.static
this makes it possible to use a cross-compiler.
> makefile.static: derive endianness without need to run binaries

- src/pageseg.c
If (res / 300) is evaluated before multiplying with 60.0,
then every resolution below 300 dpi results in csize being 0.
I believe the intention here was to linearily scale 60.0 with
the resolution, i.e. 30.0 for 150 dpi, 120.0 for 600 dpi.
Note: pixExtractTextLines() fails with the following sequence of errors without this patch:
```
*** op: c0.1; w = 0, h = 1; must both be > 0
Error in pixMorphCompSequence: sequence not valid
Error in pixConnComp: pixs not defined
Error in pixaSelectBySize: pixas not defined
Error in pixaGetBoxa: pixa not defined
Error in boxaGetCount: boxa not defined
Error in pixClipRectangles: boxa not defined
```
> pageseg.c: csize almost always 0

- src/tiffio.c
There were some function comments not tagged with `/*!` and thus not converted.
> tiffio.c: add missing doxygen style comments

- Doxyfile
- src/mainpage.txt
This includes a partial copy of the leptonica.com homepage,
a link to the homepage and a contact section.
The list of source files in Doxyfile was modified to include
src/mainpage.txt
> doxygen: add an example mainpage

- src/dewarp1.c
The example code sections in the file comment are
wrapped in \code and \endcode, which prevents doxygen
from interpreting '&', '<' and '>' as HTML tags.
> dewarp1.c: fix doxygen warning + add \code cmds

- src/grayquant.c
The conversion here was confused by nested parenthesis.
> grayquant.c: fix conversions bugs + doxygen issue

- src/kernel.c
Wrap example kernel description file format in `\code` and `\endcode` to avoid doxygen interpreting `#`.
> kernel.c: fix doxygen warnings

- .gitignore
- src/Makefile.am
The allheaders target now triggers a build of xtractprotos in the prog directory. I'm not sure if this is the proper way to do it but it's good enough to have the following work as expected.
```sh
./configure
cd src
make allheaders
```
I have assumed that allheaders.h should be written to the source directory rather than the build directory. Changing this would be difficult.
It doesn't work when building outside of the source tree but this was already broken. cpp, as invoked by xtractprotos, needs to locate endianness.h and this is written to the build directory. Perhaps xtractprotos should accept `-I` arguments or even pass all additional arguments to cpp.
> Remove Autotools build of src/xtractprotos to fix #179

- prog/pnmio_reg.c
- src/allheaders.h
- src/pnmio.c
- src/pnmiostub.c
- src/readfile.c
The netpbm tools support a new "arbitrary" format.
See: http://netpbm.sourceforge.net/doc/pam.html
It is defined by the header "P7" followed a number of
lines with tags defining the attributes. The format
of the image data is always binary, as in P4, P5 and P6.
This format supports an optional alpha channel and
will be used automagically when a Pix with 32-bpp
and 4 samples per pixel is to be written by the
pixWriteStreamPnm() or pixWriteMemPnm() functions.
Not too many viewers do yet support this format.
For verifying and converting test images the netpbm tools
can be used. To create a sample 32 bpp rgba image do:
`pngtopam --alphapam test32-alpha.png >test32-alpha.pam`
> pnmio: Add support for P7 format (PAM)

- src/pnmio.c
We can leave the header line limitation as is. I made the pnmReadNextString() gobble comment lines while searching for the next token.
> pnmio.c: gobble comments in pnmReadNextString()

- src/environ.h
Starting with Visual Studio 2015 `snprintf` is available and the macro is no longer needed.
> snprintf is available in VS2015

- .gitignore
- CMakeLists.txt
- cppan.yml
- src/CMakeLists.txt
Hi Dan,
I propose to add support of CPPAN (C++ Archive Network) for Windows build with dependencies. CPPAN is developed by me, now it's in alpha stage (but works pretty good). It's a C/C++ source package (packet) manager like CPAN (perl), CTAN (TeX) or CRAN (R-language). https://cppan.org/
Changes are quite small: one new file and couple of changes in CMakeLists.txt files that do not touch any existing build. CPPAN is activated only when 'cppan' command is invoked before build etc.
Such change is requested in #192.
> Add CPPAN support for windows builds

- src/psio2.c
Coverity report:
CID 1365497 (#1 of 1): Double free (USE_AFTER_FREE)
18. double_free: Calling free frees pointer tempfile
which has already been freed.
> psio: Fix double free

- prog/files_reg.c
Coverity report:
CID 1365496 (#1 of 2): Use after free (USE_AFTER_FREE)
7. pass_freed_arg: Passing freed pointer fname as an argument to fprintf
CID 1365496 (#2 of 2): Use after free (USE_AFTER_FREE)
8. pass_freed_arg: Passing freed pointer fname as an argument to fprintf
> files_reg: Fix use after free

- src/colorquant1.c
This fixes a new error reported by Coverity:
CID 1368189 (#1 of 1): Uninitialized pointer read (UNINIT)
> colorquant1: Remove wrong call of pixDestroy

- CMakeLists.txt
LeptonicaConfig.cmake (in build dir) was missing the include reference to the "src" folder inside the build directory. In my case another project wasn't able to find "endianness.h" which resides in that folder.
This build request adds the missing include directory inside the build dir to the include path.
> added missing include dir for templated sources

- prog/iotest.c
Coverity scan report:
CID 1364926 (#1 of 1): Negative array index read (NEGATIVE_RETURNS)
> prog/iotest: Fix potential negative array index read

- src/bmf.c
Coverity scan report:
CID 1364795 (#1 of 1): Out-of-bounds read (OVERRUN)
CID 1364908 (#1 of 1): Out-of-bounds read (OVERRUN)
CID 1364943 (#1 of 1): Out-of-bounds read (OVERRUN)
fontsize == 22 would overrun array inputfonts.
> bmf: Fix wrong check for upper bound of fontsize parameter

- src/utils.c
When adding the remainder of the cdir string to give the full value of pathout in genPathname(), the current code hardcodes a $TMPDIR string length of 4 characters (src/utils.c, lines 3004-5).
The result of this hardcoding is that the function will re-append any additional characters in the $TMPDIR string beyond "/tmp" into the pathout string when determining its full contents.
This causes failures when trying to open and write to files in $TMPDIR on Debian (and possibly other Linux distributions) that do not use plain /tmp as $TMPDIR for an unprivileged user. On Debian, a regular user's $TMPDIR is /tmp/username, not /tmp.
This commit aims to ensure that the full $TMPDIR string length is used and that only nested path entries below $TMPDIR (and not "/tmp") are appended when determining …
> Handle $TMPDIR when located under /tmp

- src/fhmtauto.c
- src/fmorphauto.c
Coverity scan reports:
CID 1365273 (#1 of 1): Unbounded source buffer (STRING_SIZE)
CID 1365364 ...
CID 1365429 ...
This fix only avoids the buffer overrun.
Supporting any length of filename would require more changes.
> Avoid some buffer overruns caused by very long file names

- src/binarize.c
Coverity scan report:
CID 1365363: Uninitialized pointer read
pixd is only assigned a value if ppixd != NULL.
> binarize: Fix use of unitialized value

- prog/cleanpdf.c
gcc output:
prog/cleanpdf.c:122:5: warning:
implicit declaration of function ‘_mkdir’ [-Wimplicit-function-declaration]
> Fix compiler warning for MinGW-w64

- autobuild
This is needed for builds with MacPorts and other platforms which
do not have libtoolize.
> autobuild: Use glibtoolize if libtoolize is unavailable

- .travis.yml
Don't use cmake-3.6.1-Linux-x86_64.sh when testing on macOS.
> travis: Activate CI for macOS

- src/memio.c
- src/memio.h
- src/pngio.c
This primarily benefits Tesseract OCR on the Windows platform because it replaces file I/O with memory operations.
> Improved png memory I/O performance.

- src/CMakeLists.txt
Similar to [tesseract#1100](https://github.com/tesseract-ocr/tesseract/pull/1100), the cmake file installs an incorrectly named library. Changes `libleptonica` to `liblept`.
> Fix cmake Release optimization level

- cmake/Configure.cmake
Small changes to add support for openjpeg 2.3.
This is in particular necessary to compile on msys2.
> add support for openjpeg 2.3

- configure.ac
The AC_CHECK_LIB default action-if-found was defining HAVE_LIBOPENJP2, which isn't used.
I did try this before but got a syntax error. I guess there was something else wrong because it works now.
> Set some configure.ac macro actions to noop where appropriate

- prog/reg_wrapper.sh
I was getting failures when gnuplot was built without it.
> Skip gnuplot tests if it is missing PNG support

- README.md
jbig2enc: The (previous) link redirects to another url, so use that url directly.
> README.md: Fix link

- src/pix.h
The MS compiler complains each time when pix.h is included.
When building tesseract, this contributes more than 300 warnings:
src\pix.h(243): warning C4305: 'initializing':
truncation from 'double' to 'l_float32' (compiling source file ...
src\pix.h(245): warning C4305: 'initializing':
truncation from 'double' to 'l_float32' (compiling source file ...
The compiler does not complain for line 244, maybe because
a 32 bit float can store 0.5 without any truncation.
Using float constant values should fix those warnings.
> Fix some compiler warnings for MS C

- prog/compfilter_reg.c
- prog/contrasttest.c
- prog/otsutest1.c
- prog/recogtest1.c
- prog/scale_reg.c
- prog/warper_reg.c
This fixes most warnings in the Appveyor CI builds:
C:\projects\leptonica\prog\compfilter_reg.c(42): warning C4838:
conversion from 'double' to 'const l_float32' requires a narrowing conversion
C:\projects\leptonica\prog\contrasttest.c(44): warning C4838:
conversion from 'double' to 'l_float32' requires a narrowing conversion
C:\projects\leptonica\prog\otsutest1.c(39): warning C4838:
conversion from 'double' to 'const l_float32' requires a narrowing conversion
C:\projects\leptonica\prog\recogtest1.c(129): warning C4838:
conversion from 'double' to 'const l_float32' requires a narrowing conversion
[C:\projects\leptonica\prog\scale_reg.c(50): warning C4838:
conversion from 'double' to 'const l_float32' requires a narrowing conversion
C:\projects\leptonica\prog\warper_reg.c(41): warning …
> Fix MS C compiler warnings

- autobuild
Tell users if pkg-config is missing instead of generating an invalid
configure script which fails with strange error messages.
> autobuild: Add check for missing pkg-config

- prog/scaleandtile.c
ncols should be positive, so show an error message otherwise.
> Fix CID 1364889 (Division or modulo by zero)

- prog/ioformats_reg.c
Commit 374e71e02ee204882921761bba5d2d85dfcb0b4e introduced a bug which
is reported by gcc:
prog/ioformats_reg.c:787:29: warning:
argument to ‘sizeof’ in ‘snprintf’ call is the same expression as the
destination; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
Fix also a typo in the 2nd fprintf statement and make sure that there is
always a valid format name:
prog/ioformats_reg.c:774:13: warning:
‘tiff_compression_name’ may be used uninitialized in this function [-Wmaybe-uninitialized]
> ioformats_reg: Fix wrong snprintf and uninitialized variable

- src/flipdetect.c
using the newest version 1.76.0 out of the box in our project outputs
```
Info in lept_mkdir: making named temp subdirectory lept/orient is disabled
```
No output.
Please note that the fix was not properly tested for all the functions.
> remove unnecessary calls to lept_mkdir

- src/bmp.h
- src/bmpio.c
The entities bfSize and bfOffBits are 32 bit values. The file's size
may be larger than the sum off bfOffBits + size of the image data.
> bmp: fix handling of bitmap file header

- src/boxfunc5.c
This also fixes a warning from LGTM:
Comparison is always false because i >= 0.
> boxfunc5: Fix loop count condition

- src/utils1.c
This fixes an error from LGTM:
Call to gmtime is potentially dangerous
> Replace insecure gmtime

- src/utils2.c
On iOS, you can't write to /tmp; each application has its own temporary directory. So we rely on the system to tell us where this directory is located.
> Handle temporary directories on iOS

- src/utils2.c
I was not able to view image results of the examples in `./prog` that used `callSystemDebug`.
`TargetConditional.h` (included if `__APPLE__`) contains the following:
```cpp
defined(__MACOS_CLASSIC__) )
#define TARGET_OS_MAC               1
#define TARGET_OS_WIN32             0
#define TARGET_OS_UNIX              0
#if !DYNAMIC_TARGETS_ENABLED
#define TARGET_OS_OSX               1
#define TARGET_OS_IPHONE            0
#define TARGET_OS_IOS               0
#define TARGET_OS_WATCH             0
#define TARGET_OS_TV                0
#define TARGET_OS_SIMULATOR         0
#define TARGET_OS_EMBEDDED          0 
#define TARGET_OS_RTKIT             0 
#endif
#define TARGET_IPHONE_SIMULATOR     TARGET_OS_SIMULATOR /* deprecated */
#define TARGET_OS_NANO              TARGET_OS_WATCH /* deprecated */ …
```
> Fix callSystemDebug on Mac OS X.

- src/tiffio.c
This fixes mtiff_reg. Add also a message for an unknown type.
> Fix writeCustomTiffTags for type `const char*`

- src/writefile.c
clang warnings:
writefile.c:423:9: warning: 'break' will never be executed [-Wunreachable-code-break]
writefile.c:427:9: warning: 'break' will never be executed [-Wunreachable-code-break]
writefile.c:438:9: warning: 'break' will never be executed [-Wunreachable-code-break]
writefile.c:442:9: warning: 'break' will never be executed [-Wunreachable-code-break]
writefile.c:446:9: warning: 'break' will never be executed [-Wunreachable-code-break]
writefile.c:450:9: warning: 'break' will never be executed [-Wunreachable-code-break]
writefile.c:454:9: warning: 'break' will never be executed [-Wunreachable-code-break]
writefile.c:458:9: warning: 'break' will never be executed [-Wunreachable-code-break]
writefile.c:462:9: warning: 'break' will never be executed [-Wunreachable-code-break] …
> writefile: Remove unreachable break statements

- src/sel1.c
gcc warning:
sel1.c:1650:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
sel1.c:1657:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
sel1.c:1664:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
sel1.c:1919:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
sel1.c:1925:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
sel1.c:1931:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
> sel1: Fix fall through warnings

- prog/boxa3_reg.c
gcc warnings:
boxa3_reg.c:40:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
boxa3_reg.c:41:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
boxa3_reg.c:65:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
boxa3_reg.c:156:1: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
> boxa3_reg: Fix old style declarations

- prog/reg_wrapper.sh
Those checks were skipped since commit 1b3c9b64ee204b3f9371cea624c959b3177c9c1d
because the `sh` shell does not support `type -P`.
> Fix checks which require gnuplot

- prog/Makefile.am
- prog/pdfio1_reg.c
- prog/pdfio2_reg.c
- prog/webpanimio_reg.c
Following #472, I did find a way to make some tests depend on others but I then found that the only reason they break in parallel is because some tests write to the same directories for seemingly no reason. `pdfio2_reg` also depends on a couple of files written by `pdfio1_reg` but it's only a few small extra lines to make it also generate the same files. All the other tests are independent so it seems silly to have this one exception.
> Fix parallel running of tests by using unique directories

- src/classapp.c
- src/fhmtauto.c
- src/fmorphauto.c
- src/gplot.c
- src/jbclass.c
- src/psio2.c
- src/sel2.c
- src/writefile.c
Using "static const int" for array lengths is a C feature too
new for Visual Studio's C compiler. Move to using #defines instead
as this compiles everywhere and has no functional difference.
> Move array lengths to #defines.

- prog/fuzzing/oss-fuzz-build.sh
I am adding the build-script from oss-fuzz.
The script will be executed like with [LibreOffice ](https://github.com/google/oss-fuzz/blob/master/projects/libreoffice/build.sh)in build.sh in oss-fuzz.
Having the build script on Leptonicas own repository gives the maintainers of Leptonica more freedom to update the fuzzers and corpora by not having to wait for the oss-fuzz team to merge the updates in.
This PR adds 2 modifications to the build script compared to the current version on oss-fuzz:
1. The license header has been removed as it is not needed here.
2. The compilation of the fuzzers has been rewritten to prevent having to update the build script every time a fuzzer is added or removed. As long as each fuzzer is named *_fuzzer.cc and is placed in the `/prog/fuzzing` directory, it …
> Added build script from oss-fuzz

- prog/fuzzing/oss-fuzz-build.sh
This PR adds back libjbig to the build script of the fuzzers.
Travis reports that [the build fails using the newly added build file](https://travis-ci.org/github/google/oss-fuzz/builds/682136051). The build-error doesn't reproduce locally consistently, and it is odd that the compiler suddenly doesn't work halfway through the build script.
I request that we add back libjbig to the build script, as the log does show some errors related to the package.
Since the build file has not been updated yet, the fuzzers are still running fine on oss-fuzz's platform.
> Added libjbig back to build script

- prog/fuzzing/pixa_recog_fuzzer.cc
Following [this PR](https://github.com/DanBloomberg/leptonica/pull/494) that had a minor slip up from my side, I am opening this PR with the simplified version of the pixa_recog_fuzzer.
This PR updates the fuzzer with Dan's corrections which were:
1. We shouldn't free pixa4, pix1, pix2.
2. pixa2 got created twice.
I have furthermore removed a couple of unused headers. 
Again, I apologize for the slip up in the last PR.
> Simplified pixa_recog_fuzzer

- src/jp2kio.c
Before this fix, calling pixWriteStreamJp2k with nlevels = 1 would create a file that could be loaded with reduction=1 and reduction=2.  If the file was created with nlevels = 2, then the file could be loaded with reduction=1, reduction=2, and reduction=4.
Calling pixWriteStreamJp2k with nlevels = 0 could trigger the default of 5, but then the you could load 6 images from the file at reduction 1, 2, 4, 8, 16, 32.
After this fix I'm getting the files with the expected number of reduced images.
> Fixed pixWriteStreamJp2k from creating an extra level.

- src/pnmio.c
Programs that read this format should be as lenient as possible,
accepting anything that looks remotely like a pixmap.
See http://www.fileformat.info/format/pbm/egff.htm.
As other software (like for example convert) seems to ignore
non-digits in the input stream, do it here, too.
> Make reading of PNM files more robust

- prog/fuzzing/oss-fuzz-build.sh
This PR updates the oss-fuzz build file to apply the general corpus to the following fuzzers:
- colorquant_fuzzer
- dewarp_fuzzer
- pix_orient_fuzzer
- pixconv_fuzzer
- blend_fuzzer
> Added seed corpus for all fuzzers

- prog/fuzzing/colorquant_fuzzer.cc
This PR adds more coverage to the colorquant fuzzer. The fuzzer is meant to keep the targets in the the colorquant files inside a single fuzzer. If it grows any bigger, we may need to split it up.
> Added more targets to colorquant_fuzzer

- prog/fuzzing/ccbord_fuzzer.cc
This PR adds a new fuzzer that targets `ccbord.c`.
A small note on this fuzzer:
It runs out of memory fairly quickly, and it seems a leak is coming from `ccbaStepChainsToPixCoords()`.
It seems to me that everything is cleaned up the way it should be, and I appreciate any comments if that isn't the case.
> Added new fuzzer

- prog/fuzzing/pixa_recog_fuzzer.cc
This PR adds pixaRemoveOutliers2() to the targets in the pixa_recog_fuzzer.
A few of the variable names have been rewritten to keep the order intact.
> Added a target to pixa_recog_fuzzer

- prog/fuzzing/compare_fuzzer.cc
Currently the fuzzer does not go past pixs2. This PR suggests a fix for that.
> Used pixCopy on pixs2 instead of pixReadMemSpix

- src/environ.h
- src/pix1.c
Leptonica contains a setPixMemoryHandler mechanism for
intercepting allocations used for the data sections of
Pix (except on Windows where it is broken/disabled).
There is no mechanism for intercepting other such
allocations though.
Here, for the sake of embedded builds that need/want to
be able to control/track all allocations, we add such a
mechanism.
If LEPTONICA_INTERCEPT_MALLOC is defined during startup,
then all calls to malloc/calloc/realloc/free are redirected
to leptonica_{malloc/calloc/realloc/free} functions that
the library assumes will be provided for it.
> Add allocation interception mechanism for embedded builds.

- cmake/Configure.cmake
Currently, when several versions of openjpeg are found, LIBJP2K_HEADER is defined several times by cmake/Configure.cmake. gcc produces a warning `warning: "LIBJP2K_HEADER" redefined` on <build_dir>/src/config_auto.h
This patch ensures that LIBJP2K_HEADER is defined only once even when several versions of openjpeg are found.
It gives priority to the most recent version of openjpeg (2.3 > 2.2 > 2.1 > 2.0).
> Avoid warning when several version of openjpeg are installed

- prog/fuzzing/adaptmap_fuzzer.cc
This PR removes the assignment of `pixContrastNorm` since the first parameter is not `NULL`
> Removed assignment in adaptmap_fuzzer

- src/boxbasic.c
- src/dnabasic.c
- src/fpix1.c
- src/numabasic.c
- src/pixabasic.c
- src/ptabasic.c
- src/sel1.c
This fixes new duplicate free and use after free errors reported by
Coverity Scan.
> Don't free data which was passed to functions with copyflag L_INSERT

- src/libversions.c
zlibVersion() is not in the static library.
> fix compilation with static zlib

- src/boxbasic.c
The written data was not terminated with '\0' if HAVE_FMEMOPEN was defined,
so using strlen on it caused a buffer overrun.
> Fix OSS-Fuzz issue 28181 (Use-of-uninitialized-value)

- src/colormap.c
- src/dewarp1.c
- src/dnabasic.c
- src/fpix1.c
- src/jp2kio.c
- src/jpegio.c
- src/numabasic.c
- src/pixabasic.c
- src/pixcomp.c
- src/pnmio.c
- src/ptabasic.c
- src/recogbasic.c
- src/sarray1.c
Add a `\0' byte like it is done by l_binaryReadStream.
> Terminate data which is written with open_memstream

- src/utils2.c
makeTempDirname() on iOS uses confstr() to get a temporary directory
because /tmp is not available to apps. macOS programs using the App
Sandbox are similarly restricted, and confstr is the recommended system
API to acquire a temporary directory path regardless.
This also fixes a bug introduced in
d15f1c24a16a65a4ae2e018a21ce9ad52b33ac64 where copying `path` to
`result` was changed from using strncpy() to stringCat(). Since the call
to confstr() already wrote to `result`, this led to the path being
incorrectly duplicated. Using stringCopy() resolves the issue.
> makeTempDirname: use confstr on macOS, and fix a bug in path generation

- src/environ.h
fmemopen is only supported from 10.13 onwards (https://news.ycombinator.com/item?id=25968777).
For earlier versions of MacOS this needs to be excluded.
> Support MacOS 10.12 and earlier

- prog/fuzzing/oss-fuzz-build.sh
Fixes the issues from here
https://github.com/DanBloomberg/leptonica/pull/635
After https://github.com/DanBloomberg/leptonica/pull/635 was merged I ran a clean build from OSS-Fuzz and noticed there was indeed a mistake. Unfortunately I had not cleared my cache in the $WORK dir previously, which meant the mistake did not show up locally. This should fix it and I believe CIFuzz will also pass this time.
> Fix minor nit to actually fix OSS-Fuzz build

- prog/iomisc_reg.c
- prog/numa3_reg.c
- src/pix5.c
The test fails in a debug build with compiler flag -ftrapv. That compiler flag modifies the code to detect illegal integer calculations.
An integer overflow was triggered because the difference of two floating point values was negative (rounding error) and the square root of negative values is undefined (NAN).
Converting NAN to integer results in an unexpected integer value.
> Fix rankhisto_reg test by fixing square root of negative number

- src/utils2.c
always use the UTF8/ANSI Win32 APIs, whether the code is built in Ansi/MBCS or Unicode (16-bit TCHAR) mode (MSVC: /Unicode flag)
---
> These show up when compiling the code in `/Unicode` mode, which is our in-house setting for all projects. Don't know if this 'reachable' via the provided cmake, as I don't use that one for Windows.
> always use the UTF8/ANSI Win32 APIs (MSVC, Unicode builds)

- configure.ac
Version 2.50 was released in 2001. Version 2.69 was released in 2012.
Version 2.70 was released in 2020. The last version is 2.71.
> configure.ac: Update minimum required autoconf version

- src/colorquant1.c
- src/graphics.c
- src/numabasic.c
- src/numafunc2.c
See also the commit messages... I hit upon these thanks to my own misuse of one these APIs (unintentionally feeding it a NUMA array of zero length) and I got some random weird results with MSVC2022, then I investigated and found `numaGetCount() == 0` was not reckoned with. Followed up that one with an overall code review and fixed all the spots where the code for the `count == 0` scenario was either non-trivial or would potentially produce random/garbage results.
(For example, a zero-length calloc on my system is a hard fail because it's way too often indicative of faulty coding somewhere, so I won't wait for `LEPT_CALLOC` to b0rk with a NULL return. This is more... pedantic than one may expect on Linuxes in general.)
> minor Numa safety patches

- src/encoding.c
- src/utils2.c
In addition, a trivial compiler warning was fixed by using an ANSI C function prototype.
>  Use macOS specific directory instead of /tmp 

- src/compare.c
- src/gplot.c
- src/regutils.h
- src/writefile.c
This makes the related functions thread safe, but calling them from different processes will still cause problems because all processes use the same filenames which are generated by using the index.
> Use atomic operations for some index variables

- src/jp2kio.c
The member variable bpp is deprecated and a synonym for the member variable prec, which already has the same value assigned to it, so remove the redundant assignment to bpp. This fixes a compiler warning:
src/jp2kio.c: In function 'pixConvertToOpjImage':
src/jp2kio.c:726:9: warning: 'bpp' is deprecated: Use prec instead [-Wdeprecated-declarations]
726 |         cmptparm[i].bpp = 8;
|         ^~~~~~~~
> Remove redundant assignment (fixes compiler warning)

- src/webpanimio.c
Those will be made nodiscard at some point.
> Check return values of WebP API functions.

- src/adaptmap.c
> Remove C99 style inline declaration

- src/allheaders.h
- src/jp2kheader.c
- src/jp2kheaderstub.c
- src/jp2kio.c
On platforms lacking `open_memstream()`, `pix{Read,Write}MemJp2k()` worked via a temporary file, but this overhead is unnecessary as openjpeg2000's `opj_stream` interface allows one to read/write directly from a memory buffer by supplying it with appropriate callbacks. This PR makes `pix{Read,Write}MemJp2k()` use this more direct mechanism on all platforms.
In addition, since `pixReadStreamJp2k()` always reads the whole stream into memory when it called `fgetJp2kResolution()`, this PR saves a bit of compute resources by in effect making `pixReadStreamJp2k()` into a wrapper for `pixReadMemJp2k()`.
> Make pix{Read,Write}MemJp2k work via direct memory access

- src/CMakeLists.txt
For CYGWIN/MSYS/MINGW, libraries should be named the same as UNIX.
> cmake: fix library name

- src/bmpio.c
Simplify also the code a little bit and remove a comment with test code.
`convertOnBigEnd32` must not be called for `ihbytes` because it is already assigned the right value which is read from `bmpih` in little endian order.
> Fix function pixReadMemBmp for big endian hosts

- prog/reg_wrapper.sh
Some older versions of /bin/sh don't work.
This was noticed in a test on Solaris 11.4 (SPARC) with sh (AT&T Research) 93u+ 2012-08-01.
Instead of using /bin/bash the script now finds bash with /usr/bin/env, so it will use the latest bash on systems like macOS.
Fix also the test for a working gnuplot.
`gnuplot -e "set terminal png"` does not return an error if the command fails, but prints an error message.
So instead of checking for an error the test now checks for a non-empty output.
This fixes `make check` on hosts with a gnuplot which does not support `set terminal png`.
> Replace sh by bash for reg_wrapper.sh and fix test for working gnuplot

- prog/partition_reg.c
- src/bmp.h
- src/bmpio.c
- src/scale2.c
The clang compiler reports several annoying warnings. Some of them have already been reported as an issue:
../src/bmpio.c:169:37: warning: taking address of packed member 'bmpih' of class or structure 'BMP_HEADER' may result in an unaligned pointer value [-Waddress-of-packed-member]
../src/bmpio.c:186:31: warning: taking address of packed member 'bmpih' of class or structure 'BMP_HEADER' may result in an unaligned pointer value [-Waddress-of-packed-member]
../src/bmpio.c:187:32: warning: taking address of packed member 'bmpih' of class or structure 'BMP_HEADER' may result in an unaligned pointer value [-Waddress-of-packed-member]
../src/bmpio.c:188:31: warning: taking address of packed member 'bmpih' of class or structure 'BMP_HEADER' may result in an unaligned pointer value …
> Fix warnings for builds with clang compiler

- Makefile.am
- configure.ac
To fix #757 by removing the broken files. It isn't simple to generate CMake config target file. Could store a generated copy from CMake, but would need to make sure it doesn't go out-of-sync and regenerate it as necessary.
> Remove broken CMake config files from autotools
